import { _db } from './connection';

export const preparedStatements = {
  getTeacherByUsername: _db.prepare('SELECT id, username, password_hash, name, is_admin FROM teachers WHERE username = ?'),
  getTeacherById: _db.prepare('SELECT id, username, name, is_admin FROM teachers WHERE id = ?'),
  getClassesByTeacher: _db.prepare('SELECT c.id, c.teacher_id, c.name, t.name as owner_name FROM classes c JOIN teachers t ON c.teacher_id = t.id WHERE c.id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  getStudentsByClass: _db.prepare('SELECT id, class_id, name, roll_number, parent_name, parent_phone, is_flagged, is_archived FROM students WHERE class_id = ? AND is_archived = 0 ORDER BY name'),
  getStudentsByClassWithArchived: _db.prepare('SELECT id, class_id, name, roll_number, parent_name, parent_phone, is_flagged, is_archived FROM students WHERE class_id = ? ORDER BY name'),
  getRecordsByClass: _db.prepare('SELECT student_id, class_id, date, status, reason FROM attendance_records WHERE class_id = ?'),
  getRecordsByDate: _db.prepare('SELECT student_id, class_id, date, status, reason FROM attendance_records WHERE date = ?'),
  getRecordsByClassAndDate: _db.prepare('SELECT student_id, class_id, date, status, reason FROM attendance_records WHERE class_id = ? AND date = ?'),
  getEventsByClass: _db.prepare('SELECT id, class_id, date, title, type, description FROM events WHERE class_id = ? ORDER BY date DESC'),
  getDailyNotesByClass: _db.prepare('SELECT date, note FROM daily_notes WHERE class_id = ?'),
  getTimetableByClass: _db.prepare('SELECT id, class_id, day_of_week, start_time, end_time, subject, lesson FROM timetable_slots WHERE class_id = ? ORDER BY day_of_week, start_time'),
  getSeatingByClass: _db.prepare('SELECT seat_id, student_id FROM seating_layout WHERE class_id = ?'),
  insertTeacher: _db.prepare('INSERT INTO teachers (id, username, password_hash, name, is_admin) VALUES (?, ?, ?, ?, 0)'),
  insertClass: _db.prepare('INSERT INTO classes (id, teacher_id, name) VALUES (?, ?, ?)'),
  insertStudent: _db.prepare('INSERT INTO students (id, class_id, name, roll_number, parent_name, parent_phone, is_flagged) VALUES (?, ?, ?, ?, ?, ?, ?)'),
  insertAttendance: _db.prepare('INSERT OR REPLACE INTO attendance_records (student_id, class_id, date, status, reason) VALUES (?, ?, ?, ?, ?)'),
  insertEvent: _db.prepare('INSERT INTO events (id, class_id, date, title, type, description) VALUES (?, ?, ?, ?, ?, ?)'),
  insertDailyNote: _db.prepare('INSERT OR REPLACE INTO daily_notes (class_id, date, note) VALUES (?, ?, ?)'),
  insertTimetableSlot: _db.prepare('INSERT INTO timetable_slots (id, class_id, day_of_week, start_time, end_time, subject, lesson) VALUES (?, ?, ?, ?, ?, ?, ?)'),
  insertSeating: _db.prepare('INSERT INTO seating_layout (class_id, seat_id, student_id) VALUES (?, ?, ?)'),
  updateStudent: _db.prepare('UPDATE students SET name = ?, roll_number = ?, parent_name = ?, parent_phone = ?, is_flagged = ?, is_archived = ? WHERE id = ? AND class_id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  updateClass: _db.prepare('UPDATE classes SET name = ? WHERE id = ? AND id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  updateEvent: _db.prepare('UPDATE events SET date = ?, title = ?, type = ?, description = ? WHERE id = ? AND class_id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  updateTimetableSlot: _db.prepare('UPDATE timetable_slots SET day_of_week = ?, start_time = ?, end_time = ?, subject = ?, lesson = ? WHERE id = ? AND class_id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  deleteClass: _db.prepare('DELETE FROM classes WHERE id = ? AND id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ? AND role = \'owner\')'),
  deleteEvent: _db.prepare('DELETE FROM events WHERE id = ? AND class_id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  deleteTimetableSlot: _db.prepare('DELETE FROM timetable_slots WHERE id = ? AND class_id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  archiveStudent: _db.prepare('UPDATE students SET is_archived = 1 WHERE id = ? AND class_id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  getStudentById: _db.prepare('SELECT s.id, s.name, s.roll_number, s.parent_name, s.parent_phone, s.is_flagged, s.is_archived FROM students s JOIN class_teachers ct ON s.class_id = ct.class_id WHERE s.id = ? AND ct.teacher_id = ?'),
  getEventById: _db.prepare('SELECT e.id, e.date, e.title, e.type, e.description FROM events e JOIN class_teachers ct ON e.class_id = ct.class_id WHERE e.id = ? AND ct.teacher_id = ?'),
  getTimetableSlotById: _db.prepare('SELECT t.id, t.day_of_week, t.start_time, t.end_time, t.subject, t.lesson FROM timetable_slots t JOIN class_teachers ct ON t.class_id = ct.class_id WHERE t.id = ? AND ct.teacher_id = ?'),
  getClassById: _db.prepare('SELECT c.id, c.teacher_id, c.name, t.name as owner_name FROM classes c JOIN teachers t ON c.teacher_id = t.id WHERE c.id = ? AND c.id IN (SELECT class_id FROM class_teachers WHERE teacher_id = ?)'),
  clearSeatingByClass: _db.prepare('DELETE FROM seating_layout WHERE class_id = ?'),
  getStudentByClassAndId: _db.prepare('SELECT id FROM students WHERE class_id = ? AND id = ?'),
  deleteSeatingBySeat: _db.prepare('DELETE FROM seating_layout WHERE class_id = ? AND seat_id = ?'),
  deleteSeatingByStudent: _db.prepare('DELETE FROM seating_layout WHERE class_id = ? AND student_id = ?'),
  insertClassTeacher: _db.prepare('INSERT OR IGNORE INTO class_teachers (class_id, teacher_id, role) VALUES (?, ?, ?)'),
  removeClassTeacher: _db.prepare('DELETE FROM class_teachers WHERE class_id = ? AND teacher_id = ?'),
  updateClassTeacherRole: _db.prepare('UPDATE class_teachers SET role = ? WHERE class_id = ? AND teacher_id = ?'),
  getClassTeachers: _db.prepare('SELECT ct.teacher_id, ct.role, t.username, t.name FROM class_teachers ct JOIN teachers t ON ct.teacher_id = t.id WHERE ct.class_id = ?'),
  isClassTeacher: _db.prepare('SELECT class_id, role FROM class_teachers WHERE class_id = ? AND teacher_id = ?'),
  countTeachers: _db.prepare('SELECT COUNT(*) as count FROM teachers'),
  getFirstTeacher: _db.prepare('SELECT id FROM teachers LIMIT 1'),
  getStudentsCount: _db.prepare('SELECT COUNT(*) as count FROM students WHERE class_id = ?'),
  getTeacherCount: _db.prepare('SELECT COUNT(*) as count FROM teachers'),
  getAllTeachers: _db.prepare('SELECT id, username, name, created_at FROM teachers'),
  getSettings: _db.prepare('SELECT key, value FROM admin_settings'),
  upsertSetting: _db.prepare('INSERT OR REPLACE INTO admin_settings (key, value) VALUES (?, ?)'),
  getAdminPassword: _db.prepare('SELECT value FROM admin_settings WHERE key = ?'),
  getStudentsCountByTeacher: _db.prepare("SELECT COUNT(*) as count FROM students s JOIN classes c ON s.class_id = c.id WHERE c.teacher_id = ?"),
  getRecordsCountByTeacher: _db.prepare("SELECT COUNT(*) as count FROM attendance_records ar JOIN classes c ON ar.class_id = c.id WHERE c.teacher_id = ?"),
  getEventsCountByTeacher: _db.prepare("SELECT COUNT(*) as count FROM events e JOIN classes c ON e.class_id = c.id WHERE c.teacher_id = ?"),
  getAllClasses: _db.prepare("SELECT c.id, c.teacher_id, c.name, t.name as teacher_name FROM classes c JOIN teachers t ON c.teacher_id = t.id"),
  insertInviteCode: _db.prepare('INSERT INTO invite_codes (code, class_id, role, created_by, expires_at) VALUES (?, ?, ?, ?, ?)'),
  getInviteCode: _db.prepare('SELECT code, class_id, role, created_by, created_at, expires_at, used_by, used_at FROM invite_codes WHERE code = ?'),
  useInviteCode: _db.prepare('UPDATE invite_codes SET used_by = ?, used_at = CURRENT_TIMESTAMP WHERE code = ?'),
  deleteInviteCode: _db.prepare('DELETE FROM invite_codes WHERE code = ?'),
  getClassInviteCodes: _db.prepare('SELECT code, role, created_by, created_at, expires_at, used_by, used_at FROM invite_codes WHERE class_id = ? ORDER BY created_at DESC'),
  deleteExpiredInviteCodes: _db.prepare("DELETE FROM invite_codes WHERE expires_at < datetime('now')"),
  insertSession: _db.prepare('INSERT INTO user_sessions (id, teacher_id, device_name, ip_address, expires_at) VALUES (?, ?, ?, ?, ?)'),
  getSession: _db.prepare('SELECT id, teacher_id, device_name, ip_address, created_at, last_active, expires_at, is_revoked FROM user_sessions WHERE id = ?'),
  getSessionsByTeacher: _db.prepare('SELECT id, device_name, ip_address, created_at, last_active, expires_at, is_revoked FROM user_sessions WHERE teacher_id = ? ORDER BY last_active DESC'),
  updateSessionActivity: _db.prepare("UPDATE user_sessions SET last_active = datetime('now') WHERE id = ?"),
  revokeSession: _db.prepare('UPDATE user_sessions SET is_revoked = 1 WHERE id = ?'),
  revokeAllSessions: _db.prepare('UPDATE user_sessions SET is_revoked = 1 WHERE teacher_id = ?'),
  deleteExpiredSessions: _db.prepare("DELETE FROM user_sessions WHERE expires_at < datetime('now')"),
  updateTeacherLastLogin: _db.prepare("UPDATE teachers SET last_login = datetime('now') WHERE id = ?"),
  countOwnedClasses: _db.prepare("SELECT COUNT(*) as count FROM class_teachers WHERE teacher_id = ? AND role = 'owner'"),
  updateTeacherPassword: _db.prepare('UPDATE teachers SET password_hash = ? WHERE id = ?'),
};